version: '3.8'

services:
    postgresql:
        container_name: postgresql
        environment:
            - POSTGRESQL_USER=${POSTGRESQL_USER}
            - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
            - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
        image: bitnami/postgresql:latest
        ports:
            - '5432:5432'
        restart: always
        volumes:
            - battleship-db:/bitnami/postgresql

volumes:
    battleship-db:
        driver: local
