version: '3.8'

services:
    postgresql:
        container_name: postgressql
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        image: postgres:bullseye
        ports:
            - '5432:5432'
        restart: always
        volumes:
            - battleship-db:/var/lib/postgresql/data

volumes:
    battleship-db:
        driver: local
